.TH "SHSTATUS" "1" "2023-03-30"  "shstatus 1.1.0" "shstatus manual"
.nh
.ad l
.SH NAME
shstatus - a simple statusline generator for i3bar and swaybar

.SH SYNOPSIS
\fIshstatus\fR [-h | --help] [-v | --version] [config-file]

.SH OPTIONS
.TP
.B -h, --help
.RS 4
Print a help message.
.RE
.TP
.B -v, --version
.RS 4
Print version information.

.SH CONFIGURATION
.TP
shstatus looks for configuration files in the following order:
.sp
.RS 4
1. \fB~/config/shstatus/config.sh\fR
.sp
2. \fB/etc/shstatus/config.sh\fR
.RE
.sp
Specifying an alternate config file overrides the default paths.
.sp
In the config file, you have to define:
.sp
.RS 4
1. A variable '\fBinterval\fR'
.sp
2. A function '\fBupdate\fR'
.RE
.sp
\fBupdate()\fR will be run every '\fBinterval\fR' seconds to update the status bar.\&
You can see an example config file in \fB/etc/shstatus/config.sh\fR.\&
It contains usage examples of every builtin block.\&
Copy it to \fB~/.config/shstatus/config.sh\fR and edit it from there.
.sp
Inside \fBupdate()\fR you can either use some builtin blocks or write your own.\&
Before using a builtin block function, you can define variables to customize its output.\&
For a list of variables, see \fBswaybar-protocol\fR(7) or \fBhttps://i3wm.org/docs/i3bar-protocol.html\fR.\&
Inside 'full_text' and 'short_text' additional variables for each block are available.\&
They are described in the next section.

.SH BUILTIN BLOCKS
.TP
\fBblock_datetime\fR <date-formatstring> <program>
.RS 4
Shows the date and time.
.sp
\fI<program>\fR can be either '\fBprintf\fR' or '\fBdate\fR'.\&
See \fBstrftime\fR(3) for how to use \fBprintf\fR, or \fBdate\fR(1) for how to use \fBdate\fR.
.sp
Available variables:
.br
\fB%date\fR - current date
.RE

.TP
\fBblock_pwvol\fR <pipewire-sink> <mute-string>
.RS 4
Shows the current volume. Works on pipewire with wireplumber.
.sp
Available variables:
.br
\fB%vol\fR        - current volume
.br
\fB%mutestatus\fR - if volume is muted, this variable contains \fI<mute-string>\fR. Otherwise it is empty.
.RE

.TP
\fBblock_pavol\fR <pulseaudio-sink> <mute-string>
.RS 4
Same as \fBblock_pwvol\fR, but for pulseaudio.
.RE

.TP
\fBblock_disk\fR <device or mountpoint>
.RS 4
Shows disk usage.
.sp
Available variables:
.br
\fB%disk\fR       - device
.br
\fB%size\fR       - disk size
.br
\fB%used\fR       - used disk space
.br
\fB%avail\fR      - available disk space
.br
\fB%usepercent\fR - percentage of used disk space
.br
\fB%mountpoint\fR - device mountpoint
.RE

.TP
\fBblock_mem\fR
.RS 4
Shows memory and swap usage.
.sp
Available variables:
.br
\fB%memtotal\fR  - total memory
.br
\fB%memused\fR   - used memory
.br
\fB%memavail\fR  - available memory
.br
\fB%swaptotal\fR - total swap
.br
\fB%swapused\fR  - used swap
.br
\fB%swapavail\fR - available swap
.RE

.TP
\fBblock_loadavg\fR
.RS 4
Shows the load average.
.sp
Available variables:
.br
\fB%load1\fR  - load average during the last 1 minute
.br
\fB%load5\fR  - load average during the last 5 minutes
.br
\fB%load15\fR - load average during the last 15 minutes
.RE

.TP
\fBblock_battery\fR <battery-name> <charging-label> <discharging-label> <full-label>
.RS 4
Shows battery information.
.sp
To list available batteries, run '\fBls /sys/class/power_supply\fR'
.sp
Available variables:
.br
\fB%percentage\fR - battery percentage
.br
\fB%status\fR     - depending on the current battery status, this contains either\&
\fI<charging-label>\fR, \fI<discharging-label>\fR or \fI<full-label>\fR.
.RE

.TP
\fBblock_backlight\fR <card> <brightness-file>
.RS 4
Shows information about the current monitor brightness.
.sp
\fI<brightness_file>\fR can be either '\fBactual_brightness\fR' or '\fBbrightness\fR'.
.br
To list available cards, run '\fBls /sys/class/backlight\fR'
.sp
Available variables:
.br
\fB%current\fR    - contents of \fB/sys/class/backlight/\fI<card>\fB/\fI<brightness-file>\fR
.br
\fB%max\fR        - contents of \fB/sys/class/backlight/\fI<card>\fB/max_brightness\fR
.br
\fB%percentage\fR - brightness percentage
.RE

.TP
\fBblock\fR
.RS 4
Generic block generator without any variables. Useful for writing your own blocks.
.RE

.SH SEE ALSO
\fBswaybar-protocol\fR(7), \fBstrftime\fR(3), \fBdate\fR(1), \fBpactl\fR(1)
.sp
i3bar protocol specification
.br
.B https://i3wm.org/docs/i3bar-protocol.html
.sp
Repository
.br
.B https://github.com/acuteenvy/shstatus
