name: CI

on:
  push:
    branches: "master"
  pull_request:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Run shellcheck
      run: shellcheck --enable=require-double-brackets,quote-safe-variables,avoid-nullary-conditions shstatus config.sh
