name: Release

on:
  push:
    tags: v*.*.*

jobs:
  release:
    name: Create the release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Create the release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create --title "$GITHUB_REF_NAME" --generate-notes "$GITHUB_REF_NAME"
